name: Pdoc

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pdoc
        run: |
          python -m pip install --upgrade pdoc3

      - name: Run pdoc
        working-directory: ./api_documentation
        run: |
          pdoc --html ./../eyecite --output-dir . --force

      - name: Run sed  # Removes insanely-long parameter definition from docs
        working-directory: ./api_documentation
        run: |
          sed -i '' 's/AhocorasickTokenizer(.*\]))/AhocorasickTokenizer()/' ./eyecite/find.html
          sed -i '' 's/AhocorasickTokenizer(.*\]))/AhocorasickTokenizer()/' ./eyecite/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: api_documentation
